# Generated by Django 4.1.6 on 2023-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('categoria', models.CharField(default='', max_length=50)),
                ('subcategoria', models.CharField(default='', max_length=50)),
                ('preco', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=300)),
                ('data_produto', models.DateField()),
                ('imagem', models.ImageField(default='', upload_to='loja/images')),
            ],
        ),
    ]
