# Generated by Django 4.1.6 on 2023-02-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_mercado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
