# Generated by Django 4.1.6 on 2023-02-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0006_rename_visualização_produto_visualizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='visualizacao',
            new_name='visualização',
        ),
    ]
