# Generated by Django 4.1.6 on 2023-02-17 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0007_rename_visualizacao_produto_visualização'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='visualização',
            new_name='visualizacao',
        ),
    ]
