# Generated by Django 4.1.6 on 2023-02-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0008_rename_visualização_produto_visualizacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinhoproduto',
            old_name='avaliacao',
            new_name='valor',
        ),
    ]
