# Generated by Django 4.1.6 on 2023-02-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0009_rename_avaliacao_carrinhoproduto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoproduto',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carrinhoproduto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
