# Generated by Django 4.1.6 on 2023-02-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0011_alter_ordempedido_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
