# Generated by Django 4.1.6 on 2023-02-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0012_alter_carrinho_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='ordempedido',
            name='carrinho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loja_app.carrinho'),
        ),
    ]
