# Generated by Django 4.1.6 on 2023-02-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0013_rename_user_cliente_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='username',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
