# Generated by Django 4.1.6 on 2023-02-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0015_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
