# Generated by Django 4.1.6 on 2023-02-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0016_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordempedido',
            old_name='ordenando_por',
            new_name='solicitante',
        ),
    ]
