# Generated by Django 4.1.6 on 2023-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0027_alter_cliente_user_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordempedido',
            name='pagamento_completo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ordempedido',
            name='pagamento_method',
            field=models.CharField(choices=[('Dinheiro na entrega', 'Dinheiro na entrega'), ('Khalti', 'Khalti')], default='Dinheiro na entrega', max_length=20),
        ),
    ]
