# Generated by Django 4.1.5 on 2023-03-09 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0031_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
