# Generated by Django 4.1.5 on 2023-03-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0033_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
