# Generated by Django 4.1.5 on 2023-03-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0036_alter_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
