# Generated by Django 4.1.5 on 2023-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0038_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordempedido',
            name='pagamento_method',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Paypal', 'Paypal')], default='Pix', max_length=20),
        ),
    ]
